name: tests-auth

on:
  pull_request:
    branches: [master]
    paths:
      - "auth/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run tests in Auth
        run: cd auth && npm install && npm run test:ci
